#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_DEBUG_MODE 1
#define CONFIG_SERIAL_DEBUG 1
#define CONFIG_VGA_DEBUG 1
#define CONFIG_MEMORY_DEBUG 1
#define CONFIG_PAGE_SIZE 4096
#define CONFIG_MAX_PAGES 1024
#define CONFIG_KERNEL_HEAP_SIZE (1024
#define CONFIG_USER_HEAP_SIZE (4
#define CONFIG_VGA_WIDTH 80
#define CONFIG_VGA_HEIGHT 25
#define CONFIG_TERM_COLOR 0
#define CONFIG_TERM_BG_COLOR 0
#define CONFIG_KEYBOARD_BUFFER 256
#define CONFIG_CMD_HISTORY 10
#define CONFIG_MAX_FILES 100
#define CONFIG_MAX_PATH_LENGTH 256
#define CONFIG_ROOT_DEVICE "/dev/hda1"
#define CONFIG_MAX_PROCESSES 32
#define CONFIG_MAX_THREADS 64
#define CONFIG_STACK_SIZE (8
#define CONFIG_NETWORK 1
#define CONFIG_TCP_IP 1
#define CONFIG_MAX_SOCKETS 32
#define CONFIG_SERIAL_PORT 0
#define CONFIG_SERIAL_BAUD 115200
#define CONFIG_TIMER_FREQ 100
#define CONFIG_USER_MODE 1
#define CONFIG_MEMORY_PROTECTION 1
#define CONFIG_STACK_PROTECTION 1
#define CONFIG_OPTIMIZATION_LEVEL 2
#define CONFIG_DEBUG_SYMBOLS 1
#define CONFIG_PROFILING 0
#define CONFIG_DEFAULT_USERNAME arc~os

#endif // CONFIG_H
